site_name: Furiosa Artifacts
site_description: Deep learning models provided by FuriosaAI
site_url: https://furiosa-ai.github.io/furiosa-artifacts

theme:
  name: material

repo_name: furiosa-ai/furiosa-artifacts
repo_url: https://github.com/furiosa-ai/furiosa-artifacts

nav:
- Overview: index.md
- How it works:
  - Publishing models: usage/publishing.md
  - Loading models: usage/loading.md
  - Running models: usage/running.md
  - Example notebook: examples/notebooks/HowToUseFuriosaModels.ipynb
- Available models: models.md
- Model description:
  - Vision:
    - Image classification:
        - EfficientNet v2 S: 'models/efficientnet_v2_s.md'
        - EfficientNet v2 M: 'models/efficientnet_v2_m.md'
        - ResNet50 v1.5: 'models/resnet50_v1.5.md'
    - Object detection:
        - SSD ResNet34: 'models/ssd_resnet34.md'
        - SSD MobileNet v1: 'models/ssd_mobilenet_v1.md'

- changelog.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - mkdocs-jupyter
